/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Schema {
  [k: string]: any;
}
/**
 * This interface was referenced by `Schema`'s JSON-Schema
 * via the `definition` "DailyMetrics".
 */
export interface DailyMetrics {
  id: string;
  date: string;
  metrics: {
    steps?: number;
    distance?: number;
    floors_climbed?: number;
    [k: string]: any;
  };
}
